WorkplaceReservation/Models/ReservationViewModel.cs
using WorkplaceReservation.Service.DTOs;

namespace WorkplaceReservation.Models
{
    public class ReservationViewModel
    {
        public List<ReservationDto> Reservations { get; set; }
        public ReservationDto Reservation { get; set; }

    }
}

WorkplaceReservation/Controllers/ReservationController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WorkplaceReservation.Models;
using WorkplaceReservation.Service.DTOs;
using WorkplaceReservation.Service.Services.EmployeeService;
using WorkplaceReservation.Service.Services.ReservationService;
using WorkplaceReservation.Service.Services.WorkplaceService;

namespace WorkplaceReservation.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;
        private readonly IEmployeeService _employeeService;
        private readonly IWorkplaceService _workplaceService;

        private IValidator<ReservationViewModel> _validator;
        public ReservationController(IReservationService reservationService, IEmployeeService employeeService, IWorkplaceService workplaceService, IValidator<ReservationViewModel> validator)
        {
            _reservationService = reservationService;
            _workplaceService = workplaceService;
            _employeeService = employeeService;
            _validator = validator;
        }
        public IActionResult Index()
        {
            var viewModel = new ReservationViewModel();
            viewModel.Reservations = _reservationService.GetAllReservation();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var employees = new EmployeeViewModel();
            employees.Employees = _employeeService.GetAllEmployee();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Employees = new SelectList(employees.Employees, "Id", "FullName");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");
            return View();
        }

        [HttpPost]
        public IActionResult Create(ReservationViewModel model)
        {
            var employees = new EmployeeViewModel();
            employees.Employees = _employeeService.GetAllEmployee();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Employees = new SelectList(employees.Employees, "Id", "FullName");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");

            ValidationResult result = _validator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Create", model);
            }

            var dto = new ReservationDto()
            {
                TimeFrom = model.Reservation.TimeFrom,
                TimeTo = model.Reservation.TimeTo,
                EmployeeId = model.Reservation.EmployeeId,
                WorkplaceId = model.Reservation.WorkplaceId,
            };
            _reservationService.CreateReservation(dto);

            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {

            var employees = new EmployeeViewModel();
            employees.Employees = _employeeService.GetAllEmployee();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Employees = new SelectList(employees.Employees, "Id", "FullName");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");

            var viewModel = new ReservationViewModel();
            viewModel.Reservation = _reservationService.GetByIdReservation(id);

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(ReservationViewModel model)
        {
            ValidationResult result = _validator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Edit", model);
            }

            var dto = new ReservationDto()
            {
                Id = model.Reservation.Id,
                TimeFrom = model.Reservation.TimeFrom,
                TimeTo = model.Reservation.TimeTo,
                EmployeeId = model.Reservation.EmployeeId,
                WorkplaceId = model.Reservation.WorkplaceId,
            };
            _reservationService.UpdateReservation(dto);

            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _reservationService.DeleteReservation(id);
            return RedirectToAction("Index");
        }
    }
}

WorkplaceReservation/Controllers/WorkplaceController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WorkplaceReservation.Models;
using WorkplaceReservation.Service.DTOs;
using WorkplaceReservation.Service.Services.EquipmentService;
using WorkplaceReservation.Service.Services.WorkplaceService;

namespace WorkplaceReservation.Controllers
{
    public class WorkplaceController : Controller
    {
        private readonly IWorkplaceService _workplaceService;
        private readonly IEquipmentService _equipmentService;
        private IValidator<WorkplaceViewModel> _validator;
        private IValidator<EquipmentForWorkplaceViewModel> _equipmentForWorkplaceValidator;
        public WorkplaceController(IWorkplaceService workplaceService, IEquipmentService equipmentService, IValidator<WorkplaceViewModel> validator, IValidator<EquipmentForWorkplaceViewModel> equipmentForWorkplaceValidator)
        {
            _workplaceService = workplaceService;
            _equipmentService = equipmentService;
            _validator = validator;
            _equipmentForWorkplaceValidator = equipmentForWorkplaceValidator;
        }
        public IActionResult Index()
        {
            var viewModel = new WorkplaceViewModel();
            viewModel.Workplaces = _workplaceService.GetAllWorkplace();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(WorkplaceViewModel model)
        {
            ValidationResult result = _validator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Create", model);
            }

            var dto = new WorkplaceDto()
            {
                Floor = model.Workplace.Floor,
                Room = model.Workplace.Room,
                Table = model.Workplace.Table,
            };
            _workplaceService.CreateWorkplace(dto);

            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = new WorkplaceViewModel();
            viewModel.Workplace = _workplaceService.GetByIdWorkplace(id);

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(WorkplaceViewModel model)
        {
            ValidationResult result = _validator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Edit", model);
            }

            var dto = new WorkplaceDto()
            {
                Id = model.Workplace.Id,
                Floor = model.Workplace.Floor,
                Room = model.Workplace.Room,
                Table = model.Workplace.Table,
            };
            _workplaceService.UpdateWorkplace(dto);

            return RedirectToAction("Index"); ;
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _workplaceService.DeleteWorkplace(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var viewModel = new EquipmentForWorkplaceViewModel();
            viewModel.EquipmentForWorkplaces = _workplaceService.GetAllEquipmentForWorkplaceId(id);

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult AddEquipment()
        {
            var equipments = new EquipmentViewModel();
            equipments.Equipments = _equipmentService.GetAllEquipment();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Equipments = new SelectList(equipments.Equipments, "Id", "Type");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");

            return View();
        }

        [HttpPost]
        public IActionResult AddEquipment(EquipmentForWorkplaceViewModel model)
        {
            var equipments = new EquipmentViewModel();
            equipments.Equipments = _equipmentService.GetAllEquipment();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Equipments = new SelectList(equipments.Equipments, "Id", "Type");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");

            ValidationResult result = _equipmentForWorkplaceValidator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("AddEquipment", model);
            }

            var dto = new EquipmentForWorkplaceDto()
            {
                Count = model.EquipmentForWorkplace.Count,
                WorkplaceId = model.EquipmentForWorkplace.WorkplaceId,
                EquipmentId = model.EquipmentForWorkplace.EquipmentId,
            };
            _workplaceService.AddEquipmentForWorkplace(dto);

            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult EditEquipment(int id)
        {
            var equipments = new EquipmentViewModel();
            equipments.Equipments = _equipmentService.GetAllEquipment();
            var workplaces = new WorkplaceViewModel();
            workplaces.Workplaces = _workplaceService.GetAllWorkplace();
            ViewBag.Equipments = new SelectList(equipments.Equipments, "Id", "Type");
            ViewBag.Workplaces = new SelectList(workplaces.Workplaces, "Id", "WorkplaceName");

            var viewModel = new EquipmentForWorkplaceViewModel();
            viewModel.EquipmentForWorkplace = _workplaceService.GetByIdEquipmentForWorkplace(id);

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult EditEquipment(EquipmentForWorkplaceViewModel model)
        {
            ValidationResult result = _equipmentForWorkplaceValidator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("EditEquipment", model);
            }

            var dto = new EquipmentForWorkplaceDto()
            {
                Id = model.EquipmentForWorkplace.Id,
                Count = model.EquipmentForWorkplace.Count,
                WorkplaceId = model.EquipmentForWorkplace.WorkplaceId,
                EquipmentId = model.EquipmentForWorkplace.EquipmentId,
            };
            _workplaceService.UpdateEquipmentForWorkplace(dto);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteEquipment(int id)
        {
            _workplaceService.DeleteEquipmentForWorkplace(id);
            return RedirectToAction("Index");
        }
    }
}

WorkplaceReservation/Views/Reservation/Create.cshtml
@model WorkplaceReservation.Models.ReservationViewModel

@{
    ViewData["Title"] = "Create Reservation";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly"></div>
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Reservation.EmployeeId" class="control-label">Employee</label>
                <select asp-for="Reservation.EmployeeId" class="form-control" asp-items="ViewBag.Employees">
                    <option value="" hidden>Select Employee</option>
                </select>
                <span asp-validation-for="Reservation.EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.WorkplaceId" class="control-label">Workplace</label>
                <select asp-for="Reservation.WorkplaceId" class="form-control" asp-items="ViewBag.Workplaces">
                    <option value="" hidden>Select Workplace</option>
                </select>
                <span asp-validation-for="Reservation.WorkplaceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.TimeFrom" class="control-label">Time From</label>
                <input asp-for="Reservation.TimeFrom" class="form-control" />
                <span asp-validation-for="Reservation.TimeFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.TimeTo" class="control-label">Time To</label>
                <input asp-for="Reservation.TimeTo" class="form-control" />
                <span asp-validation-for="Reservation.TimeTo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">Back to Reservations</a>
</div>

WorkplaceReservation/Views/Reservation/Edit.cshtml
@model WorkplaceReservation.Models.ReservationViewModel

@{
    ViewData["Title"] = "Edit Reservation";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly"></div>
        <form asp-action="Edit">
            <input type="hidden" asp-for="Reservation.Id" />
            <div class="form-group">
                <label asp-for="Reservation.EmployeeId" class="control-label">Employee</label>
                <select asp-for="Reservation.EmployeeId" class="form-control" asp-items="ViewBag.Employees"></select>
                <span asp-validation-for="Reservation.EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.WorkplaceId" class="control-label">Workplace</label>
                <select asp-for="Reservation.WorkplaceId" class="form-control" asp-items="ViewBag.Workplaces"></select>
                <span asp-validation-for="Reservation.WorkplaceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.TimeFrom" class="control-label"></label>
                <input asp-for="Reservation.TimeFrom" class="form-control" />
                <span asp-validation-for="Reservation.TimeFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.TimeTo" class="control-label"></label>
                <input asp-for="Reservation.TimeTo" class="form-control" />
                <span asp-validation-for="Reservation.TimeTo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">Back to Reservations</a>
</div>

WorkplaceReservation/Views/Reservation/Index.cshtml
@model WorkplaceReservation.Models.ReservationViewModel

@{
    ViewData["Title"] = "Reservations";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
</div>

<table class="table table-bordered table-light">
    <thead class="table-success">
        <tr>
            <th>
                FirstName
            </th>
            <th>
                LastName
            </th>
            <th>
                Time From
            </th>
            <th>
                Time To
            </th>
            <th>
                Floor
            </th>
            <th>
                Room
            </th>
            <th>
                Table
            </th>
            <th>
                <a asp-action="Create" class="btn btn-success btn-sm">Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Reservations) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Table)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Edit</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                <a asp-controller="Workplace" asp-action="Details" asp-route-id="@item.WorkplaceId" class="btn btn-info btn-sm">Equipments Info</a>
            </td>
        </tr>
}
    </tbody>
</table>